name: CI/CD for React App with PM2 Serve

on:
  push:
    branches:
      - main  # jab main branch par push hoga tab deploy chalega

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: ğŸ“¥ Checkout Code
        uses: actions/checkout@v4

      - name: ğŸ“¦ Install Dependencies
        run: yarn install

      - name: ğŸ— Build React App
        run: yarn build

      - name: ğŸš€ Start/Restart with PM2 Serve
        run: |
          pm2 delete my-app || true
          pm2 serve out 3000 --name "my-app" --spa
          pm2 save
